server:
  port: 8082

spring:
  application:
    name: storage-service

  datasource:
    url: jdbc:postgresql://localhost:5432/authDb
    username: postgres
    password: 5432

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
    session:
      timeout: 30m

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: user-files

  session:
    store-type: redis
    redis:
      namespace: spring:session

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG